Applying  Warshall Algorithm to reachability matrix

1) Load the reachability matrix

In [1]:
#Set Wd 
import os
import pandas as pd 
import numpy as np

os.chdir("C:\\Users\\gabri\\Desktop\\Data collection and analysis\\PhD Chapters\\Challenges")

irm = pd.read_csv("reachability matrix.csv", header=None)
labels = list(range(1,len(irm)+1)) 
irm.index = labels 
irm.columns = labels
irm

    1   2   3   4   5   6   7   8   9   10  11
1    1   1   1   0   1   1   0   0   1   0   0
2    0   1   1   0   0   0   0   1   0   0   0
3    0   0   1   0   0   0   0   1   0   1   0
4    0   0   0   1   0   0   0   0   0   0   0
5    1   0   1   0   1   0   1   0   0   1   0
6    0   0   0   1   0   1   0   0   0   0   0
7    0   0   0   0   0   0   1   1   1   1   0
8    0   0   0   0   0   0   1   1   1   1   0
9    0   0   0   0   0   0   0   0   1   0   0
10   0   0   0   0   0   0   0   1   0   1   0
11   0   0   0   0   0   0   0   1   0   1   1

In [3]:
test = irm.loc[9,1] and irm.loc[1,2]
# test
s = (11,11)
frm = pd.DataFrame(np.zeros(s, dtype=int))
frm.index = [1,2,3,4,5,6,7,8,9,10,11]
frm.columns = [1,2,3,4,5,6,7,8,9,10,11]

for k in range(1,len(irm)): 
    print(irm.loc[1,8] or (irm.loc[1,k] and irm.loc[k,8]))

0
1
1
0
0
0
0
0
0
0

In [5]:
len(irm)
r = list(range(1,len(irm)+1))
r

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

Convert the data frame to a matrix

rm = df.to_numpy()
rm

Implementation or Warshall Algorithm

def warshall(M): 
    n = len(M)
    W = M 
    for k in range(n):
        for i in range(n): 
            for j in range(n): 
                W[i,j] = W[i,j] or (W[i,k] and W[k,j])
    return W

In [4]:
def warshall(M): 
    W = M 
    s =(len(M),len(M))
    frm = pd.DataFrame(np.zeros(s, dtype=int))
    labels = list(range(1,len(M)+1)) 
    frm.index = labels
    frm.columns = labels
    for k in range(1,len(M)+1):
        for i in range(1,len(M)+1): 
            for j in range(1,len(M)+1): 
                if frm.loc[i,j] == 0:
                    frm.loc[i,j] = W.loc[i,j] or (W.loc[i,k] and W.loc[k,j])
    return frm

Run the algorithm and export to csv

In [5]:
#frm = warshall(irm)
frm = []
frm = warshall(irm)
frm

    1   2   3   4   5   6   7   8   9   10  11
1    1   1   1   1   1   1   1   1   1   1   0
2    0   1   1   0   0   0   1   1   1   1   0
3    0   0   1   0   0   0   1   1   1   1   0
4    0   0   0   1   0   0   0   0   0   0   0
5    1   1   1   0   1   1   1   1   1   1   0
6    0   0   0   1   0   1   0   0   0   0   0
7    0   0   0   0   0   0   1   1   1   1   0
8    0   0   0   0   0   0   1   1   1   1   0
9    0   0   0   0   0   0   0   0   1   0   0
10   0   0   0   0   0   0   1   1   1   1   0
11   0   0   0   0   0   0   1   1   1   1   1